module.exports = {
  name: "Default Express App",
  MONGO_DB_URL: "localhost",
  MONGO_DB_PORT: "27017",
  MONGO_DB_DATABASE: "mail",
  MONGO_USERNAME: "root",
  MONGO_PASSWORD: "example",
  RAABITMQ_USERNAME: "rabbitmq",
  RAABITMQ_PASSWORD: "rabbitmqpass",
  RABBITMQ_URL: "localhost",
  RABBITMQ_PORT: "5672",
  RABBITMQ_QUEUE_NAME: "mailer",
  SMTP_HOST: "smtp.ethereal.email",
  SMTP_PORT: 587,
};
